base_url = "https://yellow-coast-0f5f9a61e.2.azurestaticapps.net"

title = "gleason-alia"
description = "A collection of miscellaneous thoughts"
author = "Michael Gleason"
theme = "tabi"

compile_sass = true
build_search_index = true



[markdown]
highlight_code = true
highlight_theme = "css"
smart_punctuation = true

[extra]
theme_switcher = true
skin = "mint"
copy_button = true

menu = [
    { name = "about", url = "about", trailing_slash = true },
    { name = "github", url = "https://github.com/mgleason97", trailing_slash = false },
]

